### ISSUE TITLE
Where did conversation history go? Where did the message I typed go? Why no sane provider defaults? Why no OpenAI-like providers?

### ISSUE THREAD

**Issue by atljoseph** [twinnydotdev/twinny#355]
Yeah, I gave this another try because Matt Williams said to on youtube. 
I do like this extension, especially the way the chat can be triggered by highlighting and choosing an option.
Not to mention, it is capable... And fast.
Now that it is working, there are things that don't work right.
Am running on latest VSCode on Ubuntu. Extension version is v3.17.30. 

(1) No history is stored or displayed, but there is a page for it.
No matter what, conversation history is always empty. Couldn't find a setting to affect this either. There are no console log errors to speak of. 

(2) Template page never remembers what was last selected. Feels really brittle... There is no Save button. Selections disappear when i come back in to the extension.

(3) If i have a chat, and then close the side bar, everything is lost... The chat is gone when i re-enter the extension... Like it never happened. Related to (1) above, but in relation to the last opened convo... That should stay open, if you desire a positive user experience. Right now, it is the roughest of rough.

(4) The most annoying of all is that No matter the conversation being lost, the last text i entered and never sent is lost. Not stellar.

(5) The code completion is out of this world WRONG about every suggestion. Am I doing something wrong? Tried all sorts of models, including ollama and openrouter everything. The output is completely off point, every time.

(6) Why does a user have to choose a provider if you ALSO make the user enter the api endpoint? Do you know how frustrating that is? Why not take the extra hour or so to infer those based on provider. Ollama embedding and chat completion endpoints are set in stone, so are all the others, pretty much. Or just make it not a required field and use a default if no override is set. So painful.

(7) Why no providers to be able to use OpenAI-like APIs?  To use OpenRouter or anything else with this just becomes a burden. I understand the "sticker" says "privacy", but isn't that at the discretion of the people who input the settings? I don't like an app making that decision for me 100%.

**Comment by rjmacarthy** [comment]
Hello and thank you for the detailed feedback. 

I want to be clear and upfront that this is an open-source project I maintain in my free time. While I aim to make it useful, I can't provide the same level of support as commercial products.

Regarding your issues:

Although I cannot be sure the conversation history/storage issues sound like a permissions problem. The extension needs write access to store data to the global VSCode storage API. This works fine for other users (including myself), I'd recommend checking VSCode permissions, other than that I don't know.

For FIM and code completion: "base" or "code" models tend to work most of the time not instruct models. Here's the docs which explains tested and working models.

https://twinnydotdev.github.io/twinny-docs/general/supported-models/

For providers and API setup, yes the setup is manual. Could I pre-configure everything? Sure. Will I? Probably not. I built this thing to be adaptable because I'm too lazy to pre-configure everything and keep up with all the new providers.

With all that being said: You're welcome to:

- Try to troubleshoot (sharing error logs would help)
- Submit a PR if you want to improve something
- Try other VSCode AI assistants if you need something more polished

All the best!

**Comment by Routhinator** [comment]
RE: History - I am also seeing this - but I do not see any way to grant the plugin to the mentioned Storage API. I do not see any options for that in the plugin options or in VSCode? Can you please document how we are supposed to do this?

Is this possibly a bug specific to VSCodium?
